name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Build
        run: sbt -v +assembly

      - name: Build image
        run: docker build -t jartest .

      - name: Run tests in container
        run: docker run -t jartest
